# Generated by Django 3.2.16 on 2024-07-06 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20240706_1403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post_id',
            new_name='id_post',
        ),
    ]
