# Generated by Django 3.2.16 on 2024-07-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_rename_post_id_comment_id_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='id_post',
            new_name='post',
        ),
    ]
